# Generated by Django 4.2.5 on 2023-09-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
