# Generated by Django 4.2.4 on 2023-08-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('slug', models.SlugField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updeted_at', models.DateTimeField(auto_now=True)),
                ('integer', models.IntegerField()),
                ('ii_stock', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
