# Generated by Django 4.2.4 on 2023-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larisa', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='ii_stock',
            field=models.BooleanField(verbose_name='I LOVE YOU'),
        ),
    ]
