
+ user with jwt token
+ product CRUD
+ rating, comment
+ permissions
+ swagger

+ favorits, dislike       
+ pagination filter serch

+ celery   -> brew install redis (добавить в req.txt redis, celery)
+ order
+ карусель


+ cache
+ logging
+ cors
+ media
+ admin


- tests
- fake chat


deploy