
+ user with jwt token
+ product CRUD
+ rating, comment
+ permissions
+ swagger

+ favorits, dislike       
pagination filter serch =================================================

deploy
celery

order
tests
cache
logging
cors
media
admin
карусель
fake chat

